server:
  port: 8071
  servlet:
    context-path: /movingwalls

info:
    app.name: Moving Walls Service
    build.version: 0.1.0-XXX

spring:
 jpa:
    database: h2
    show-sql: true

 datasource:
    platform: h2
    url: jdbc:h2:mem:FMS
    username: sa
    password:
    driverClassName: org.h2.Driver